name: Build FeastFlow Checker Windows EXE

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyQt6 pyinstaller Pillow
      
      - name: Build Windows EXE
        run: |
          cd FeastFlow_Checker
          pyinstaller FeastFlow_Checker.spec
      
      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: FeastFlow-Checker-Windows
          path: FeastFlow_Checker/dist/FeastFlow_Checker.exe
          retention-days: 90
      
      - name: Create Release Info
        run: |
          echo "Build completed successfully!" > FeastFlow_Checker/dist/BUILD_INFO.txt
          echo "Build Date: $(date)" >> FeastFlow_Checker/dist/BUILD_INFO.txt
          echo "Python Version: 3.11" >> FeastFlow_Checker/dist/BUILD_INFO.txt
          echo "PyQt6 Version: Latest" >> FeastFlow_Checker/dist/BUILD_INFO.txt
      
      - name: Upload Build Info
        uses: actions/upload-artifact@v4
        with:
          name: Build-Info
          path: FeastFlow_Checker/dist/BUILD_INFO.txt
